language: ruby
rvm:
  - 2.4
services:
  - postgresql
before_install:
  - gem install bundler
before_script:
  - psql -c 'create database "trainers-hub_test";' -U postgres
script:
  - rubocop app/ lib/
  - bundle exec rspec
